# Generated by Django 2.2.5 on 2019-11-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='badrooms',
        ),
        migrations.AddField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
    ]
