# Generated by Django 2.2.5 on 2019-12-27 01:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20191226_1724'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reservation',
            managers=[
                ('obejcts', django.db.models.manager.Manager()),
            ],
        ),
    ]
